# Generated by Django 5.2.6 on 2025-09-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('prof', 'Professeur'), ('student', 'Étudiant'), ('employee', 'Employé'), ('alumni_student', 'Ancien Étudiant'), ('alumni_prof', 'Ancien Professeur'), ('alumni_employee', 'Ancien Employé'), ('membersite', 'Membre du site')], default='membersite', max_length=20),
        ),
    ]
