# Generated by Django 5.2.6 on 2025-09-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('prof', 'Professeur'), ('student', 'Étudiant'), ('employee', 'Employé'), ('alumni_student', 'Ancien Étudiant'), ('alumni_prof', 'Ancien Professeur'), ('alumni_employee', 'Ancien Employé'), ('abonne', 'Abonné(e)')], default='abonne', max_length=20),
        ),
    ]
