# Generated by Django 5.2.6 on 2025-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
