# Generated by Django 5.2.6 on 2025-09-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_activity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Activité du père'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dernière école fréquentée'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_activity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Activité de la mère'),
        ),
    ]
