# Generated by Django 5.2.6 on 2025-09-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_father_activity_student_last_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/birth_certificates/', verbose_name="Extrait d'archive (Acte de naissance)"),
        ),
        migrations.AddField(
            model_name='student',
            name='last_school_report',
            field=models.FileField(blank=True, null=True, upload_to='students/last_school_reports/', verbose_name='Dernier carnet scolaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de l'élève"),
        ),
    ]
