# Generated by Django 5.2.6 on 2025-10-02 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_academicyear_options_and_more'),
        ('programs', '0003_subject'),
        ('students', '0006_alter_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Métier du père'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Métier de la mère'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(help_text="Année académique de l'étudiant", on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, help_text='Certificat de naissance (PDF max 3MB)', null=True, upload_to='students/certificates/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(help_text='Classe assignée', on_delete=django.db.models.deletion.CASCADE, to='programs.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_school_report',
            field=models.FileField(blank=True, help_text='Bulletin de la dernière école (PDF max 3MB)', null=True, upload_to='students/reports/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_activity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_activity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_phone',
        ),
    ]
