# Generated by Django 5.2.6 on 2025-10-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_options_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, default='Non renseigné', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_job',
            field=models.CharField(blank=True, default='Non renseigné', max_length=100, null=True),
        ),
    ]
