# Generated by Django 5.2.6 on 2025-09-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_value_welcome_delete_valuemission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='homepage.slide')),
            ],
        ),
    ]
