# Generated by Django 5.2.6 on 2025-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('KINDERGARTEN', 'Kindergarten'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire')], max_length=50, unique=True),
        ),
    ]
