# Generated by Django 5.2.6 on 2025-09-16 12:46

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_academicyear_options_and_more'),
        ('programs', '0003_subject'),
        ('students', '0006_alter_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('trimester', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('step', models.CharField(choices=[('S1', 'Etape 1'), ('S2', 'Etape 2'), ('S3', 'Etape 3'), ('S4', 'Etape 4'), ('S5', 'Etape 5')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='programs.classroom')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('classroom', 'academic_year', 'trimester', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='program', chained_model_field='program', on_delete=django.db.models.deletion.CASCADE, to='programs.classroom')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('student', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='classroom', chained_model_field='classroom', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.subject')),
                ('report_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportsession')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('report_session', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='programs.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='programs.subject')),
            ],
            options={
                'unique_together': {('classroom', 'subject', 'academic_year')},
            },
        ),
    ]
