# Generated by Django 5.2.6 on 2025-09-15 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_academicyear_options_and_more'),
        ('programs', '0003_subject'),
        ('students', '0006_alter_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='programs.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sessions', to='academics.step')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='academics.trimester')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('classroom', 'academic_year', 'trimester', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='programs.subject')),
                ('report_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='reports.reportsession')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('report_session', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='programs.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='programs.subject')),
            ],
            options={
                'unique_together': {('classroom', 'subject', 'academic_year')},
            },
        ),
    ]
