# Generated by Django 5.2.6 on 2025-09-16 19:46

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_subject'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='report_session',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='classroom', chained_model_field='classroom', on_delete=django.db.models.deletion.CASCADE, to='reports.reportsession'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='classroom', chained_model_field='classroom', on_delete=django.db.models.deletion.CASCADE, to='programs.subject'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
    ]
