# Generated by Django 5.2.6 on 2025-09-16 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsession',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsession',
            name='step',
            field=models.CharField(choices=[('S1', 'Etape 1'), ('S2', 'Etape 2'), ('S3', 'Etape 3'), ('S4', 'Etape 4'), ('S5', 'Etape 5')], default='S1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportsession',
            name='trimester',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2),
        ),
    ]
