# Generated by Django 5.2.6 on 2025-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_grade_options_alter_grade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
