# Utilise une image Node pour construire le site
FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Utilise Nginx pour servir le site statique
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Si tu as un fichier de config nginx personnalisé, décommente la ligne suivante
# COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]