services:
  - type: web
    name: college-quisqueya-backend
    env: python
    plan: free

    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: |
      cd backend
      gunicorn backend.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.deployment_settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: college-quisqueya-backend
          property: host
