services:
  - type: web
    name: college-quisqueya-backend
    env: python
    plan: free

    # ============================================
    # 🔧 Étape de build
    # ============================================
    buildCommand: |
      ./build.sh

    # ============================================
    # 🚀 Commande de démarrage
    # ============================================
    startCommand: |
      cd backend
      gunicorn backend.wsgi:application

    # ============================================
    # 🌍 Variables d’environnement Render
    # ============================================
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.deployment_settings

      - key: PYTHON_VERSION
        value: 3.13.4

      - key: SECRET_KEY
        generateValue: true

      # Base de données Render
      - key: DATABASE_URL
        sync: false

      # Hôte public (Render)
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: college-quisqueya-backend
          property: host
