# Generated by Django 5.2.6 on 2025-09-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollife', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schoollife.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
