# Generated by Django 5.2.6 on 2025-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollife', '0004_galleryitem_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
