# Generated by Django 5.2.6 on 2025-10-03 20:56

import schoollife.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollife', '0005_alter_galleryitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/', validators=[schoollife.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/', validators=[schoollife.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[schoollife.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[schoollife.models.validate_image_size]),
        ),
    ]
