# Generated by Django 5.2.6 on 2025-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politique', 'Politique'), ('genie', 'Génie'), ('sport', 'Sport'), ('education', 'Éducation'), ('technologie', 'Technologie'), ('metier', 'Métier professionnel'), ('divertissement', 'Divertissement'), ('economie', 'Économie'), ('environnement', 'Environnement'), ('sante', 'Santé'), ('societe', 'Société'), ('culture', 'Culture'), ('religion', 'Religion & Spiritualité'), ('histoire', 'Histoire'), ('sciences', 'Sciences'), ('innovation', 'Innovation'), ('ia', 'Intelligence Artificielle'), ('startups', 'Startups'), ('developpement', 'Développement personnel'), ('entrepreneuriat', 'Entrepreneuriat'), ('carriere', 'Carrière & Emploi'), ('leadership', 'Leadership'), ('voyage', 'Voyage & Tourisme'), ('gastronomie', 'Gastronomie'), ('mode', 'Mode & Style'), ('musique', 'Musique'), ('cinema', 'Cinéma & Séries'), ('jeuxvideo', 'Jeux vidéo')], default='divertissement', max_length=30, verbose_name='Catégorie'),
        ),
    ]
