# Generated by Django 5.2.6 on 2025-09-08 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_name'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, help_text='Département (optionnel)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_year',
            field=models.ForeignKey(help_text='Année académique en cours', on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(help_text="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(help_text='Poste occupé (ex: secrétaire, comptable, surveillant, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
