# Generated by Django 5.2.6 on 2025-09-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_name'),
        ('professors', '0001_initial'),
        ('programs', '0002_remove_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='classrooms',
            field=models.ManyToManyField(help_text='Classes déjà enregistrées, à choisir par le professeur', to='programs.classroom'),
        ),
        migrations.AddField(
            model_name='professor',
            name='program',
            field=models.ForeignKey(default=1, help_text='Programme auquel le professeur appartient (à choisir parmi les programmes enregistrés)', on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.CharField(default='Non renseigné', help_text='Liste des matières enseignées, séparées par des virgules (à saisir par le professeur)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='academic_year',
            field=models.ForeignKey(help_text='Année académique active choisie par le professeur', on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
    ]
