# Generated by Django 5.2.6 on 2025-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professor_classrooms_professor_program_and_more'),
        ('programs', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='subjects',
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(related_name='professors', to='programs.subject'),
        ),
    ]
