# Generated by Django 5.2.6 on 2025-09-08 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('employee', 'Employee')], help_text="Type d'alumni", max_length=20)),
                ('year_left', models.PositiveIntegerField(help_text="Année de départ de l'école")),
                ('promo_name', models.CharField(help_text='Nom de la promotion', max_length=100)),
                ('years_interval', models.CharField(help_text="Intervalle de temps passé à l'école (ex: 2018-2025)", max_length=20)),
                ('proof_document', models.FileField(blank=True, help_text="Document prouvant le passage à l'école", null=True, upload_to='alumni_docs/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
